# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Avada-second-app"
client_id = "7eeb87c781133327bca9e4e87a6ad03d"
application_url = "https://rg-usb-during-blow.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://rg-usb-during-blow.trycloudflare.com/auth/shopify/callback",
  "https://rg-usb-during-blow.trycloudflare.com/authSa/shopify/callback",
  "https://rg-usb-during-blow.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thai-store-com.myshopify.com"
